name: ClusterFuzzLite PR fuzzing
on:
  pull_request:
    paths:
      - plugin/PySrc/**
      - test/PySrc/tests/*_fuzzer.py
permissions: read-all
jobs:
  PR:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.sanitizer }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
          - address
        # Override this with the sanitizers you want.
        # - undefined
        # - memory
    steps:
      - name: Build Fuzzers (${{ matrix.sanitizer }})
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: python
          sanitizer: ${{ matrix.sanitizer }}
          # Optional but recommended: used to only run fuzzers that are affected
          # by the PR.
          # See later section on "Git repo for storage".
          # storage-repo: https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/OWNER/STORAGE-REPO-NAME.git
          # storage-repo-branch: main   # Optional. Defaults to "main"
          # storage-repo-branch-coverage: gh-pages  # Optional. Defaults to "gh-pages".
      - name: Run Fuzzers (${{ matrix.sanitizer }})
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          fuzz-seconds: 600
          mode: 'code-change'
          sanitizer: ${{ matrix.sanitizer }}
          output-sarif: true
          # Optional but recommended: used to download the corpus produced by
          # batch fuzzing.
          # See later section on "Git repo for storage".
          # storage-repo: https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/OWNER/STORAGE-REPO-NAME.git
          # storage-repo-branch: main   # Optional. Defaults to "main"
          # storage-repo-branch-coverage: gh-pages  # Optional. Defaults to "gh-pages".
