# This workflow will install node dependencies, build, and run tests

name: html-build

on:
  push:
    paths:
      - 'html/**'
      - '.github/**'
  pull_request:
    paths:
      - 'html/**'
      - '.github/**'

permissions:
  contents: read

jobs:
  html-build:
    runs-on: ubuntu-latest
    if: >
      github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name !=
      github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Set up Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '20'
      - name: Install Node dependencies
        run: |
          cd html
          npm ci
          cd ..
      - name: Build Javascript
        run: |
          cd html
          npm run build
          cd ..
      - name: Test JavaScript
        run: |
          cd html
          npm test
          cd ..
